FROM dockerhub.private.wso2.com/wso2esb-analytics:5.0.0

COPY esb-analytics/carbon/ /mnt/wso2-artifacts

COPY artifacts/mysql-connector-java-5.1.34-bin.jar /mnt/wso2-artifacts/repository/components/lib/

USER root